# Generated by Django 4.1 on 2022-08-27 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_profile_email_profile_name_profile_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
