# Generated by Django 4.1 on 2022-08-29 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_pic',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.profile')),
                ('profile_pic', models.ImageField(default='empty_images.jpg', null=True, upload_to='profiles/myimages')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
