# Generated by Django 4.1.1 on 2022-09-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_remove_profile_username_remove_profile_pic_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_user',
            field=models.IntegerField(),
        ),
    ]
