# Generated by Django 4.1.1 on 2022-09-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_profile_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
